// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5RcTOzhg3j_9viwyVxl1JWjo2C-yWoLg',
    appId: '1:69651022873:web:f6ffa3d548445453b4d688',
    messagingSenderId: '69651022873',
    projectId: 'todo-c8336',
    authDomain: 'todo-c8336.firebaseapp.com',
    storageBucket: 'todo-c8336.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMTzKmGWGOsKvfko9LraBfKgJ3Je8Ydg',
    appId: '1:69651022873:android:eef238f4205b007db4d688',
    messagingSenderId: '69651022873',
    projectId: 'todo-c8336',
    storageBucket: 'todo-c8336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLdoTXhuRjqpZu2FPw3aluEGicjlT1TE',
    appId: '1:69651022873:ios:4658926175a15bebb4d688',
    messagingSenderId: '69651022873',
    projectId: 'todo-c8336',
    storageBucket: 'todo-c8336.firebasestorage.app',
    iosBundleId: 'com.example.testverst4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLdoTXhuRjqpZu2FPw3aluEGicjlT1TE',
    appId: '1:69651022873:ios:4658926175a15bebb4d688',
    messagingSenderId: '69651022873',
    projectId: 'todo-c8336',
    storageBucket: 'todo-c8336.firebasestorage.app',
    iosBundleId: 'com.example.testverst4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5RcTOzhg3j_9viwyVxl1JWjo2C-yWoLg',
    appId: '1:69651022873:web:ca25d9255208c2d7b4d688',
    messagingSenderId: '69651022873',
    projectId: 'todo-c8336',
    authDomain: 'todo-c8336.firebaseapp.com',
    storageBucket: 'todo-c8336.firebasestorage.app',
  );

}